Lesson 5
ReDI-School/nrw-html-and-css-2021-spring pull request #13
Opened 2021-03-28 20:59 UTC by impactmass

2021-03-30 21:18 UTC, otaruMendez commented on lesson5/index.md
> +- `Unordered lists` - are used to mark up lists of items for which the order of the items doesn't matter. ([MDN](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/HTML_text_fun
```suggestion
- `Unordered lists` - are used to make up lists of items for which the order of the items doesn't matter. ([MDN](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/HTML_text_fundamentals))
```

2021-03-30 21:51 UTC, otaruMendez commented on .prettierrc
> +{
Did you add this on purpose?

2021-03-30 21:52 UTC, otaruMendez reviewed
Do we leave these `lesson5/Checkpoint5/about.html` `lesson5/Checkpoint5/projects.html` blank?

2021-03-30 21:59 UTC, otaruMendez commented on lesson5/homework/ShoppingListExample.html
> +<!DOCTYPE html>
Is the plan for the students to copy and modify this for the homework task?

2021-03-30 22:02 UTC, otaruMendez commented on lesson5/index.md
> +- Explain characteristics of a block and inline elements. <https://www.w3schools.com/html/html_blocks.asp>
```suggestion
- Explain characteristics of block and inline elements. <https://www.w3schools.com/html/html_blocks.asp>
```

2021-03-31 06:36 UTC, angelsvirkov commented
I believe the about and projects html files should have some skeleton content . For example:

```html
<!DOCTYPE html>
 
 otaruMendez 9 hours ago • 
edited 
 Collaborator

Is the plan for the students to copy and modify this for the homework task?
If yes, we could drop a message about this file in the homework section in the class note.

	Reply…
Resolve conversation
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>About</title>
</head>
<body>
<h1>About</h1>
</body>

</html>
```

2021-03-31 06:54 UTC, angelsvirkov requested changes

2021-03-31 06:54 UTC, angelsvirkov commented on lesson5/homework/ShoppingListExample.html
> +<!DOCTYPE html>
The idea is that they look at `ShoppingList.png` and try to produce the html for it. This file is just an example what the html could look like

2021-03-31 06:54 UTC, angelsvirkov commented on lesson5/Checkpoint5/index.html
> +          <a href="projects.html">Projects</a>
Aren't we missing the `<li>` here?

2021-03-31 06:54 UTC, angelsvirkov commented on lesson5/Checkpoint5/index.html
> +      <ul>
GJ 💯

2021-03-31 06:54 UTC, angelsvirkov commented on lesson5/Checkpoint5/index.html
> +      <hr />
Shouldn't the `<hr>` be in between different sections?

2021-03-31 06:54 UTC, angelsvirkov commented on lesson5/Checkpoint5/index.html
> +      <img src="./photo.jpg" alt="A photo of me enjoying sunset at the beach">
GJ for adding an example `photo.jpg`

2021-03-31 06:54 UTC, angelsvirkov commented on lesson5/index.md
> +
I would simply add 
```suggestion
This section covers the html `<base>` tag and its use cases. The following examples should be covered.
```

2021-03-31 06:54 UTC, angelsvirkov commented on lesson5/index.md
Let's add hyperlink to the glossary 
```suggestion
- `Hyperlink` - Hyperlinks are any links that are comprised of text, image, video, etc. A hypertext is a form of hyperlink, which uses text. More information on the differences between hyperlink and hypertext can be found [here](https://www.geeksforgeeks.org/hyperlink-vs-hypertext/#:~:text=Difference%20between%20Hyperlink%20and%20Hypertext%3A&text=Hypertext%20contains%20the%20Non%2Dlinear,video%2C%20images%2C%20and%20graphics.).
```

2021-03-31 08:20 UTC, impactmass commented on lesson5/Checkpoint5/index.html
> +          <a href="projects.html">Projects</a>
oops. Yes...thanks for catching that.

2021-03-31 08:20 UTC, impactmass commented on lesson5/Checkpoint5/index.html
> +      <hr />
Fair point. Adjusted.

2021-03-31 08:20 UTC, impactmass commented on lesson5/homework/ShoppingListExample.html
> +<!DOCTYPE html>
yes, what Angel said.

2021-03-31 08:20 UTC, impactmass commented on .prettierrc
> +{
yes, I did. I use prettier in formatting. By default it uses 4 spaces. This setting makes it use 2 spaces since that is what the other lesson notes use.

2021-03-31 08:29 UTC, impactmass commented on lesson5/homework/ShoppingListExample.html
> +    <ul>
@angelsvirkov I made a change to this list. I removed the `<hr>`s in the list. `hr` (technically) should not be a direct child of ul/ol.  - [Ref](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul)

2021-03-31 08:30 UTC, angelsvirkov commented on lesson5/homework/ShoppingListExample.html
> +    <ul>
Alright 👍

2021-03-31 08:33 UTC, otaruMendez commented
LGTM! Thanks @impactmass 👍

2021-03-31 08:34 UTC, angelsvirkov approved these changes
Also good from my side 🌮

2021-03-31 08:37 UTC, merged