Add static site generator
ReDI-School/nrw-html-and-css-2021-spring pull request #2
Opened 2021-03-16 20:40 UTC by impactmass

2021-03-16 21:40 UTC, impactmass commented on index.md
> +* Vincent
please confirm that I included all the teachers

2021-03-16 21:42 UTC, impactmass commented on index.md
> +* Vincent
I'm not sure Christopher is here any longer

2021-03-17 08:22 UTC, angelsvirkov requested changes
I found some minor suggestions here and there. Overall looks good 💯

2021-03-17 08:22 UTC, angelsvirkov commented on _config.yml
> +description: This is the homepage of the "NRW HTML & CSS" course at ReDI School || Fall 2020
```suggestion
description: This is the homepage of the "NRW HTML & CSS" course at ReDI School || Spring 2020
```

2021-03-17 08:22 UTC, angelsvirkov commented on index.md
> +* Vincent
I don't know if I can confirm. Should we ping Takuya maybe?

2021-03-17 08:22 UTC, angelsvirkov commented on .gitignore
> +_site
1. I am using a VS code plugin which tracks every file change in a folder called `.history`. This is a plan B in cases something goes wrong with git and my changes (untracked files) are gone or something else fails. So I would like to have it. 

2. Moreover, I was thinking about using this plugin with students, as well because it automatically tracks file changes but we can discuss this later

```suggestion
.history
_site
```

2021-03-17 08:22 UTC, angelsvirkov commented on Gemfile
> +
If you are free for a call at some point, I would like to get to know how the whole setup works :)

2021-03-17 08:22 UTC, angelsvirkov commented on lesson3/index.md
> +---
So the teacher folder is going to be removed?

2021-03-17 08:22 UTC, angelsvirkov commented on lesson4/index.md
> +# Terms
In my lesson 2 I actually renamed this to `Glossary & Terminology` as it makes more sense I guess. Would you agree to change this?

2021-03-17 20:25 UTC, impactmass commented on .gitignore
> +_site
Sounds good. I didn't look at this change properly, sorry it got deleted

2021-03-17 20:25 UTC, impactmass commented on Gemfile
> +
Sure. Whenever you have some time

2021-03-17 20:25 UTC, impactmass commented on index.md
> +* Vincent
1. I'll just add all the names I find on the teacher's mailing list for now
2. We will need to discuss that with ReDI. For now, I'll leave it as first names

2021-03-17 20:25 UTC, impactmass commented on lesson3/index.md
> +---
hmmm, yea, do we still need it around?

2021-03-17 20:25 UTC, impactmass commented on lesson4/index.md
> +# Terms
That sounds good. I agree. I will update.

2021-03-17 20:35 UTC, angelsvirkov commented on lesson3/index.md
> +---
Maybe yes for the beginning at least

2021-03-17 20:40 UTC, merged