lesson 7 notes
ReDI-School/nrw-html-and-css-2021-spring pull request #24
Opened 2021-04-01 16:36 UTC by impactmass

2021-04-04 20:04 UTC, impactmass commented
@otaruMendez @angelsvirkov you can start a review on this. The main content is ready, but still working on the checkpoint + homework

2021-04-05 16:03 UTC, otaruMendez commented on lesson7/index.md
> +
Maybe we can add `fieldset` and `legend` elements to this list.

2021-04-05 16:05 UTC, otaruMendez commented on lesson7/index.md
> +- `<input type="checkbox">`
I thought you already treated the `input` element in Part 1, is this intional?

2021-04-06 06:37 UTC, angelsvirkov commented on lesson7/index.md
> +- HTML form - An HTML form is used to collect user input. [Source](https://www.w3schools.com/html/html_forms.asp)
The word `caveat` is in my opinion often used in programming. I think it deserves a place in the glossary section

2021-04-06 06:44 UTC, angelsvirkov requested changes
The content looks good to me. Added suggestions for glossary, resources, homework and exercises

2021-04-06 06:44 UTC, angelsvirkov commented on lesson7/index.md
> +- HTML form - An HTML form is used to collect user input. [Source](https://www.w3schools.com/html/html_forms.asp)
The word `caveat` is in my opinion often used in programming. I think it deserves a place in the glossary section

2021-04-06 06:44 UTC, angelsvirkov commented on lesson7/index.md
> +- [MDN's HTML Forms Page](https://developer.mozilla.org/en-US/docs/Learn/Forms)
Do we maybe have further resources for form caveats (or security issues) with forms. I am not sure I fully understood the content of that section `Online Form Caveats` so maybe a resource link would be useful if we have one

2021-04-06 06:44 UTC, angelsvirkov commented on lesson7/index.md
>  For next session please prepare this and that, etc...
Lesson 7 is the last lesson before introducing CSS in lesson 8. I am not sure if it makes a lot of sense to give heavy homework. What would you say for a homework such as - `Do a recap of everything we have covered for HTML so far` (lesson1-7), because students really need to know these super basic things before diving in on the more difficult topic

2021-04-06 06:44 UTC, angelsvirkov commented on lesson7/index.md
> +Students should complete Checkpoint 7 as described above.
1 - For checkpoint 7, what should the contact page contain? Should it be a form which sends an email to the site owner?  

2 - I am not sure I saw it, but is there any other practical exercise with forms and if yes, how are we going to make that work (online mock server?, local mock server, etc.)? Do we have a solution for this already

2021-04-06 09:50 UTC, impactmass commented on lesson7/index.md
> +- HTML form - An HTML form is used to collect user input. [Source](https://www.w3schools.com/html/html_forms.asp)
Good point. But after reviewing the class again, I have to drop this section due to time constraint.

2021-04-06 09:50 UTC, impactmass commented on lesson7/index.md
> +- [MDN's HTML Forms Page](https://developer.mozilla.org/en-US/docs/Learn/Forms)
Actually, after reviewing the class again, I have to drop this section due to time constraint.

2021-04-06 09:50 UTC, impactmass commented on lesson7/index.md
> +Students should complete Checkpoint 7 as described above.
1. The page will contain a simple form like the image lesson7/form-sketch.png. From my findings, setting up a place where the form content will be sent to (e.g a server, or email) will be a bit advanced. If we have time at the end of the semester, we can do it. Otherwise, I think we can remove the contact form from the project. 

2. the practical exercise during the class is to work on the checkpoint. I will make a mock server where their forms will submit to - only for the purposes of learning as described in point 1 above.

2021-04-06 09:50 UTC, impactmass commented on lesson7/index.md
>  For next session please prepare this and that, etc...
I like your suggestion of: `Do a recap of everything we have covered for HTML so far`. And maybe also telling the students to make sure they have completed all the checkpoints taught so far.

2021-04-06 09:50 UTC, impactmass commented on lesson7/index.md
> +- `<input type="checkbox">`
After reviewing the time for each section, I have to drop this section entirely.

2021-04-06 09:50 UTC, impactmass commented on lesson7/index.md
> +
After reviewing the time for each section, I have to drop this section entirely. Maybe we can do a Part 2 of Forms in the future?

2021-04-06 09:52 UTC, angelsvirkov commented on lesson7/index.md
>  For next session please prepare this and that, etc...
Yes, good point. Let's include those 2 things
- recap
- make sure to have reached checkpoint 7 and if not to align your code with the code from checkpoint 7 and ask questions in Classroom channel if they need help

2021-04-06 09:55 UTC, angelsvirkov commented on lesson7/index.md
> +Students should complete Checkpoint 7 as described above.
So let's keep the contact form in checkpoint 7 and assume that it is working. I would not like to remove it at all. Maybe at the end of the semester we can give students further resources on how to make this work or else they can swap the contact form with plain list of contact details. BUt for now I would definitely like to have it in (although not functioning) so that we have a richer website

2021-04-06 09:57 UTC, angelsvirkov commented on lesson7/index.md
> +
I checked the new ETA sum and its 1hour and 30 mins after removing these sections. Are you sure that this would be enough? Maybe you can keep Part 2 as (Optional) and cover only the parts that you have time for

2021-04-06 09:57 UTC, impactmass commented on lesson7/index.md
> +Students should complete Checkpoint 7 as described above.
sounds good. I will add checkpoint 7 folder

2021-04-06 10:27 UTC, impactmass commented on lesson7/index.md
> +
Hmmm? I see 1hr40m. And with 10mins break, that's 1h 50mins. 

However, I just added it back now. Let's see how it goes.

2021-04-06 18:37 UTC, impactmass commented
**Task Force: In this class, please take a few mins to explain to the students about the Checkpoints and how we are using it to build the Portfolio Project, and ensure they are up to date.**

2021-04-07 11:17 UTC, impactmass commented
All comments addressed.

2021-04-07 14:36 UTC, angelsvirkov requested changes
I have covered everything and it looks cool. Two minor suggestions only

2021-04-07 14:36 UTC, angelsvirkov commented on lesson7/index.md
> +2. Form Tags (Part 1)
3. Form Tags (Part 2 - if there is time)

2021-04-07 14:36 UTC, angelsvirkov commented on lesson7/checkpoint7/contact.html
> +  <meta http-equiv="X-UA-Compatible" content="IE=edge">
Is this line needed? I think we have not taught students about these meta attributes

2021-04-07 16:55 UTC, impactmass commented on lesson7/index.md
> +2. Form Tags (Part 1)
```suggestion
2. Form Tags (Part 1)
3. Form Tags Part 2 (if there is time)
```

2021-04-07 16:55 UTC, impactmass commented on lesson7/checkpoint7/contact.html
> +  <meta http-equiv="X-UA-Compatible" content="IE=edge">
Honestly, I don't know. It is produced by VS Code Emmet auto-complete for basic html structure. I won't worry about it (IMO). It's not everything that we have to teach.

2021-04-07 16:55 UTC, impactmass commented on lesson7/checkpoint7/contact.html
> +  <meta http-equiv="X-UA-Compatible" content="IE=edge">
```suggestion
```

2021-04-07 16:57 UTC, impactmass commented on lesson7/checkpoint7/contact.html
> +  <title>Document</title>
```suggestion
  <title>Contact</title>
```

2021-04-07 17:04 UTC, angelsvirkov approved these changes
Gj with everything

2021-04-07 17:09 UTC, otaruMendez approved these changes

2021-04-07 17:10 UTC, otaruMendez commented
Looks good to me! Can I merge? @impactmass

2021-04-07 17:12 UTC, impactmass commented
yes. Thanks you two for reviewing!

# 🚢 🇮🇹

2021-04-07 17:13 UTC, merged