first draft of lesson 12
ReDI-School/nrw-html-and-css-2021-spring pull request #30
Opened 2021-04-11 17:26 UTC by neyoalao

please kindly go through the draft. Add your contributions and things that needs corrections.

2021-04-12 06:50 UTC, angelsvirkov requested changes
Thanks for the PR @neyoalao :). Here is my feedback.

I agree that lesson 12 should include the simple css display types and the css position. I think at the end of the lecture students will be too tired and we will have too little time to cover `CSS Pseudo Elements 1`, so I suggest dropping this topic completely. Regarding the section `Styling a button`, I am not particularly sure. We actually have anchor tags that are like buttons for us and we have already included such a section in lesson 10 I think. Here is a [reference](https://github.com/ReDI-School/nrw-html-and-css-2021-spring/pull/27#issuecomment-817313873). 

So to sum up I think in this lesson we should cover
- CSS Display Types I
- CSS Position
( we have to see if we could sneak in some more things here ). Maybe a small DevTools tutorial once again to make students confident using it (could be done at the beginning of the class)

2021-04-12 06:50 UTC, angelsvirkov commented on lesson12/index.md
> +- understand what display block, inline and inline-block
```suggestion
- understand what display block, inline, inline-block, and none
```

2021-04-12 06:50 UTC, angelsvirkov commented on lesson12/index.md
> +## 2. CSS Display types
I suggest having CSS Display types I because at later point in time we would also introduce flex and grid which are more advanced display types that we can label as `CSS Display Types II` and `CSS Display Types III`
```suggestion
## 2. CSS Display types I
```

2021-04-12 06:50 UTC, angelsvirkov commented on lesson12/index.md
> +title: Lesson 11 - CSS Position and Display types
```suggestion
title: Lesson 12 - CSS Position and Display types I
```

2021-04-12 06:50 UTC, angelsvirkov commented on lesson12/index.md
> +# CSS Icons Links and Lists
```suggestion
# CSS Position and Display types I
```

2021-04-13 19:57 UTC, angelsvirkov commented
@neyoalao , as agreed during the task force meeting we have created the following content for lesson 13. Would you please close this PR and open a new one for lesson 13. Feel free to do this after finishing your class. Thank you. 

```
# Lesson 13 Display

1. Normal flow
2. CSS Display types
3. CSS Floats

## 1. CSS Display types

students get understanding of what display types and different elements with their default display times

Only those: `block, inline and inline-block`

- understand what display block, inline and inline-block
- how to change the default `display` of elements to align differently. E.g. `anchor` tags are by default inline but you can make them block.

- explain that height and width don't work for in-line elements. it also doesn't allow margin-top and bottom


ETA: 50min

## 3. Teach Float

Use in the context of the navigation and footer. So only these things.

ETA: 50min
```

2021-04-14 10:33 UTC, neyoalao commented
@angelsvirkov thanks for the update. If I understand correctly, I have to elaborate on the topics and checkpoint of lesson 13 right?

2021-04-14 11:06 UTC, angelsvirkov commented
> @angelsvirkov thanks for the update. If I understand correctly, I have to elaborate on the topics and checkpoint of lesson 13 right?

Yes exactly. The trickiest point is the checkpoint. Also we need to make sure to fill in the Glossary, Resources, and the Homework

2021-04-14 19:41 UTC, closed without merging