Updates to Lesson 10, Lesson 10 Checkpoint
ReDI-School/nrw-html-and-css-2021-spring pull request #34
Opened 2021-04-16 01:13 UTC by vickjoeobi

Dear @impactmass @angelsvirkov, 

Find the updated version of Lesson 10. 

Vincent

2021-04-16 06:39 UTC, angelsvirkov commented
@vickjoeobi , why was this PR closed and re-opened again. I think we lost the feedback from @impactmass

2021-04-16 06:43 UTC, vickjoeobi commented
@angelsvirkov i noticed that the feedback from @impactmass was alot. So I quickly implemented it and resubmitted another pull request. 

See the title and observe it's different from the previous

2021-04-16 21:01 UTC, impactmass commented
Hey @vickjoeobi, for next time, I think it is better we keep the discussion in one PR. It's helps the review process. Sorry I didn't mean for my comments on the other PR to be a lot. 

I have spotted a few changes here as well. I understand that you are quite busy, so I will merge this and update after.

2021-04-16 22:17 UTC, vickjoeobi commented
Apologies for that. I would keep that in mind subsequently. 

Thanks.

2021-04-18 16:29 UTC, vickjoeobi commented
> Hey @vickjoeobi, for next time, I think it is better we keep the discussion in one PR. It's helps the review process. Sorry I didn't mean for my comments on the other PR to be a lot.
> 
> I have spotted a few changes here as well. I understand that you are quite busy, so we can merge this and update after.

What is the status of this PR?
CC:  @angelsvirkov @impactmass

2021-04-18 16:29 UTC, angelsvirkov commented
@vickjoeobi , could you please use a branch on this Repo next time because I cannot check out the files locally which makes it easier for me to check some stuff. I am currently reviewing the PR

2021-04-18 16:50 UTC, angelsvirkov requested changes
I have done a first round of review (only concentrating on the actual content of `index.md`). After this is solved I would concentrate on the changes of the checkpoint. Here is my feedback so far:

2021-04-18 16:50 UTC, angelsvirkov commented on lesson10/index.md
> +title: Lesson 11 - CSS Icons Links and Lists
```suggestion
title: Lesson 11 - CSS Links and Lists
```

2021-04-18 16:50 UTC, angelsvirkov commented on lesson10/index.md
> +# CSS Icons Links and Lists
```suggestion
# CSS Links and Lists
```

2021-04-18 16:50 UTC, angelsvirkov commented on lesson10/index.md
> +This section teaches students how to deciorate various links found on the website. This includes but not Menu links, External links etc. The section covers:
```suggestion
This section teaches students how to decorate various links via CSS. This includes menu links, external links  and others. In particular, the section covers the following points:
```

2021-04-18 16:50 UTC, angelsvirkov commented on lesson10/index.md
> +- Explain the various states that a link can exist in (e.g Visited, Hover, Focus, Active)
```suggestion
- What are the various states that a link can have (e.g Visited, Hover, Focus, Active)?
```

2021-04-18 16:50 UTC, angelsvirkov commented on lesson10/index.md
> +- Explain that browsers apply `default styles` on links.
```suggestion
- What are the `default styles`, which are applied by the browser to links?
```

2021-04-18 16:50 UTC, angelsvirkov commented on lesson10/index.md
> +- How do we convert links to buttons, and style them with CSS?
What do you mean by this `how do we convert links to buttons`? Can you give me an example

2021-04-18 16:50 UTC, angelsvirkov commented on lesson10/index.md
> +2. CSS List sytling
```suggestion
2. CSS List Styling
```

2021-04-18 16:50 UTC, angelsvirkov commented on lesson10/index.md
> +1. CSS Link styling
```suggestion
1. CSS Link Styling
```

2021-04-18 16:50 UTC, angelsvirkov commented on lesson10/index.md
> +This section is all about Lists. Either creating lisits using CSS or designing the already created HTML list. This is important because in the process of designing webpages, lists are always used. Th
The section is not all about lists because there is a lot more about lists which has been covered during the HTML Lists class. Moreover, I avoid strong definitive adjectives such as `always used`. Therefore, here is my suggestion:

```suggestion
An important aspect of a webpage design is styling lists. Therefore this section teaches students how to create lists using CSS. Moreover, students learn how to design an already created HTML list. In particular the section covers the following points:
```

2021-04-18 16:50 UTC, angelsvirkov commented on lesson10/index.md
> +- Recap of HTML list
let's add a hyperlink here

```suggestion
- Recap of [HTML Lists](https://redi-school.github.io/nrw-html-and-css-2021-spring/lesson5/#2-lists)
```

2021-04-18 16:50 UTC, angelsvirkov commented on lesson10/index.md
> +- Different list Item makers such as Circle, square, upper-roman etc. (using `list-style-type`)
```suggestion
- Using the `list-style-type` css rule to apply different list item makers such as circle, square, upper-roman, etc.
```

2021-04-18 16:50 UTC, angelsvirkov commented on lesson10/index.md
> +- Styling the list colours.
I would include these in one point
```suggestion
- Changing list styles such as positioning of the list item marker, changing the default style, using different list colours and others.
```

2021-04-18 16:50 UTC, angelsvirkov commented on lesson10/index.md
> +Exercises should be done along each sections and making the students repeat some process and adding their own styles.
```suggestion
Exercises should be done along each section and should help students add their own styles.
```

2021-04-18 16:50 UTC, angelsvirkov commented on lesson10/index.md
> +2. Define some list (Ordered and unordered), and design it with colors.
Here is my idea for point 2. During lecture 5 we added the following homework point => https://redi-school.github.io/nrw-html-and-css-2021-spring/lesson5/homework/ShoppingList.png

I would suggest that we use the same shopping list content but this time we style the tags in some special way. We then make a screenshot of the final product and ask students to write the css for these links. We can also give them a link to the existing HTML -> https://github.com/ReDI-School/nrw-html-and-css-2021-spring/blob/master/lesson5/homework/ShoppingListExample.html

2021-04-18 16:50 UTC, angelsvirkov commented on lesson10/index.md
> +- [CSS Links](https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Styling_links)
We try to add resources in an alphabetical order. I would also suggest that we we do not duplicate hypertext because it will look like a bug on the final website.
```suggestion
- [CSS Links - MDN](https://developer.mozilla.org/en-US/docs/Learn/CSS/Styling_text/Styling_links)
- [CSS Links - W3S](https://www.w3schools.com/css/css_link.asp)
- [CSS Lists - MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Lists_and_Counters)
- [CSS Lists - W3S](https://www.w3schools.com/css/css_list.asp)
```

2021-04-18 16:50 UTC, angelsvirkov commented on teacher/Lesson6Feedback.md
> +# Teacher Feedback of Lesson 6
GJ for this feedback 💯

2021-04-19 07:03 UTC, angelsvirkov requested changes
The changes to the checkpoint look good to me. I have added 3 suggestions and 1 out of scope fix for the navigation bar

2021-04-19 08:50 UTC, vickjoeobi commented on lesson10/index.md
> +2. Define some list (Ordered and unordered), and design it with colors.
@angelsvirkov this seems a little confusing to me.

2021-04-19 08:53 UTC, vickjoeobi commented
Apart from one of the changes requested by @angelsvirkov which i am still confused about, i have implemented all the requested changes.

2021-04-19 10:07 UTC, angelsvirkov commented on lesson10/index.md
> +2. Define some list (Ordered and unordered), and design it with colors.
This is how I am going to explain it to students, for example:
- For your homework, please look at this screenshot of a shopping list and write the corresponding HTML and CSS to create a page that contains the list as displayed in the screenshot. 


Does this help?

2021-04-19 11:28 UTC, vickjoeobi commented on lesson10/index.md
> +2. Define some list (Ordered and unordered), and design it with colors.
Sure it helps. Will add this immediately.

2021-04-19 11:29 UTC, vickjoeobi commented
All changes updated.

2021-04-19 11:54 UTC, angelsvirkov commented on lesson10/index.md
> +2. Define some list (Ordered and unordered), and design it with colors.
@vickjoeobi , but adding one sentence is not enough. How do we expect students to do this task when there is no screenshot?

2021-04-19 11:56 UTC, angelsvirkov commented on lesson10/index.md
> +- How do we convert links to buttons, and style them with CSS?
@vickjoeobi , I am still not sure what is meant by this point even after you added a partial sentence `example converting links of Navigation to button like.` (which btw is probably missing the "For")

2021-04-19 13:32 UTC, vickjoeobi commented on lesson10/index.md
> +2. Define some list (Ordered and unordered), and design it with colors.
should I add the link? https://redi-school.github.io/nrw-html-and-css-2021-spring/lesson5/homework/ShoppingList.png

2021-04-19 14:03 UTC, angelsvirkov commented on lesson10/index.md
> +2. Define some list (Ordered and unordered), and design it with colors.
No because that is the screenshot for lesson5 homework. It has no styles. If we would like to include this homework point then we need to prepare an example and take a screenshot of it. BUt I think it is taking too much time to discuss so I would be fine to not add this as a homework point

2021-04-19 14:28 UTC, angelsvirkov commented
@vickjoeobi there is only one unresolved comment 
- https://github.com/ReDI-School/nrw-html-and-css-2021-spring/pull/34#discussion_r615782438

2021-04-19 14:46 UTC, vickjoeobi commented on lesson10/index.md
> +- How do we convert links to buttons, and style them with CSS?
Updated, can you confirm it is now cool.

2021-04-19 14:48 UTC, angelsvirkov approved these changes
Thanks for the work. Merging PR 👍

2021-04-19 14:48 UTC, merged