first draft of lesson 13
ReDI-School/nrw-html-and-css-2021-spring pull request #37
Opened 2021-04-17 23:15 UTC by neyoalao

Please kindly glance through the first draft of lesson 13.
I currently have no idea what to implement for the checkpoint!

2021-04-18 16:29 UTC, angelsvirkov commented
> I currently have no idea what to implement for the checkpoint!

I think we would have a better picture once we have checkpoints 10, 11 and 12. So for now it is not possible I think

2021-04-18 21:43 UTC, neyoalao commented
I can't agree more.
Could you have a look at the write-up? I would like to know if there is something I need to remove or add!

2021-04-19 20:58 UTC, impactmass commented
The display types (inline/inline-block) together with CSS Floats can help achieve a horizontal layout for the nav links. Maybe that can be one of the exercise(s) and checkpoint here. We can already write about it in the notes to guide the teacher.   
<img width="474" alt="checkpoint_-_CodeSandbox" src="https://user-images.githubusercontent.com/5229321/115302230-824ec780-a162-11eb-8ca3-7d7ccaef5a0e.png">
The `display: inline-block;` is briefly mentioned in Lesson 10, here we can explain it better.

2021-04-20 18:00 UTC, angelsvirkov commented on lesson13/index.md
> +1. CSS Positions
```suggestion
3. CSS Float
```

2021-04-20 18:12 UTC, angelsvirkov commented
@neyoalao let's pull out the `nav`  bar out of header and also add it to all pages in this checkpoint

2021-04-20 18:20 UTC, angelsvirkov commented on lesson13/index.md
> +
```suggestion
> Disclaimer: Lesson 12 (link to it) already covered the characteristics and differences between inline boxes and block boxes. This sections of the lecture goes into more details about the different display types and  explains how to change the default display type with the css `display` rules.
```

2021-05-01 17:07 UTC, impactmass commented
helping here

2021-05-01 19:47 UTC, impactmass commented on lesson13/index.md
> +    - All of this can be seen in Checkpoint 13
```suggestion
    - Check Checkpoint 13 for a example with completed steps
```

2021-05-03 06:42 UTC, angelsvirkov requested changes
It looks good. I think you might have enough time to properly create a nav menu. I have suggested one part that we might also need to teach

2021-05-03 06:42 UTC, angelsvirkov commented on lesson13/index.md
> +## 2. The `display` Property
Lesson 12 teaches `inline` and `block` . I told the students that they would learn about `inline-block` in Lesson 13, as well. I was under the impression we were about to teach that here. Should we add it `display: inline-block;`

2021-05-03 12:11 UTC, impactmass commented on lesson13/index.md
> +    - Check Checkpoint 13 for a example with completed steps
```suggestion
    - Check Checkpoint 13 for example with completed steps
```

2021-05-03 12:11 UTC, impactmass commented on lesson13/index.md
> +- Revision: What does block level and inline elements mean?
```suggestion
- Revision: What does block level and inline elements mean?
- Discuss `display: inline-block`. How is it similar/different to block and inline?
```

2021-05-03 12:11 UTC, impactmass commented on lesson13/index.md
> +## 2. The `display` Property
Good. I've added it above.

2021-05-03 12:17 UTC, angelsvirkov approved these changes
Looks good to me

2021-05-03 12:18 UTC, angelsvirkov commented
@impactmass , you can proceed with merging if you are done with it

2021-05-03 14:59 UTC, merged