Lesson 18
ReDI-School/nrw-html-and-css-2021-spring pull request #50
Opened 2021-05-24 10:32 UTC by impactmass

2021-05-25 16:56 UTC, angelsvirkov requested changes
I really like the notes for this class as they really scratch the surface and are a good an easy guide to follow (was even refreshing for me). Thank you. I have added some suggestions plus an idea for the checkpoint

2021-05-25 16:56 UTC, angelsvirkov commented on lesson18/index.md
> +Note: Teachers are not limited to the examples shown in this note.
Good job adding this small disclaimer

2021-05-25 16:56 UTC, angelsvirkov commented on lesson18/index.md
> +# Introduction
The introduction is not mentioned in the class agenda. Is this intended? I am fine with it

2021-05-25 16:56 UTC, angelsvirkov commented on lesson18/index.md
> +css rule with the different classes as shown below, the last one will be used.
This can create a confusion. Is it the last one in the class definition or is it the last one in the class usage. Lets maybe make this clearer in the sentence.

2021-05-25 16:56 UTC, angelsvirkov commented on lesson18/index.md
> +---
There are some typos. I used a VS Code extension to check this
![image](https://user-images.githubusercontent.com/18263878/119536080-f9423600-bd88-11eb-88f2-8152fda356cd.png)

2021-05-25 16:56 UTC, angelsvirkov commented on lesson18/index.md
> +- [Calculating CSS Specificity Value](https://css-tricks.com/specifics-on-css-specificity/#calculating-css-specificity-value)
Let's keep the alphabetical order as discussed in the past. And I would also add one additional link
```suggestion
- [Calculating CSS Specificity Value](https://css-tricks.com/specifics-on-css-specificity/#calculating-css-specificity-value)
- [MDN Cascade and Inheritance Page](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance)
- [MDN Specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity)
- [Precedence in CSS](https://css-tricks.com/precedence-css-order-css-matters/)
```

2021-05-25 16:56 UTC, angelsvirkov commented on lesson18/index.md
> +Inheritance is another crucial part of CSS Cascade. Inheritance is how some CSS rules set on a parent element are inherited by their child elements. In this section, we want to show examples where a
I had difficulties reading the second sentence. I think we can put some punctuation in the sentence (a.k.a. non-restrictive clause - revising my English Grammar classes :D) 
```suggestion
Inheritance is another crucial part of CSS Cascade. Inheritance is how some CSS rules, which are set on parent elements, are inherited by their child elements. In this section, we want to show examples where a property value (e.g color, font-family) is inherited by an element.
```

2021-05-25 16:56 UTC, angelsvirkov commented on lesson18/index.md
> +- Specificity determines, which CSS rule is applied by the browsers.
The rest of the classes have the glossary word highlighted . I removed the comma here (Also relates to my research for commas -> :D  if you wanna read more https://prowritingaid.com/grammar/1008080/Should-I-use-a-comma-before-which-)
```suggestion
- `Inheritance` is a process of receiving values of properties by a child element from its parent element.
- `Specificity` determines which CSS rule is applied by the browsers.
```

2021-05-25 16:56 UTC, angelsvirkov commented on lesson18/index.md
> +- Look in your project and review how specific your CSS selectors are. See if you can find places you could be using lower specificity while still achieving your styling.
I think we can create a checkpoint which adds comment to the code and styles. We can search for places in the code to label them with some comments such as 
```
/* This CSS rule cascades / is more specific over ...etc */ 
```

We can also give students the homework to try to find these places if there are any and label them. What do you think?

2021-05-25 16:56 UTC, angelsvirkov commented on lesson18/index.md
> +# Cascade, Specificity and Inheritance
There are no ETAs but maybe that is intended I guess? Should we then include somewhere one global ETA or should we leave it as it is implicit that the whole class deals with this content

2021-05-25 20:19 UTC, impactmass commented on lesson18/index.md
> +css rule with the different classes as shown below, the last one will be used.
```suggestion
css rule with the different classes as shown below, the last one that comes last in the source code will be used (i.e padding: 0)
```

2021-05-25 20:34 UTC, impactmass commented on lesson18/index.md
> +# Cascade, Specificity and Inheritance
Yes, I decided to leave it implicit. 
Sorry I forgot to add a comment for you about it.

2021-05-25 20:43 UTC, impactmass commented on lesson18/index.md
> +css rule with the different classes as shown below, the last one that comes last in the source code will be used (i.e padding: 0)
```suggestion
css rule with the different classes as shown below, the last one that 
comes last in the source code will be used (i.e padding: 0)
```

2021-05-26 06:48 UTC, angelsvirkov submitted a review, later dismissed
@impactmass , this PR looks good to me. Should we merge and take the last unresolved point in a separate checkpoint PR, if we agree to do it?

2021-05-26 10:44 UTC, impactmass commented on lesson18/index.md
> +- Look in your project and review how specific your CSS selectors are. See if you can find places you could be using lower specificity while still achieving your styling.
Good idea. I'll do that.

2021-05-26 10:45 UTC, impactmass commented
Yes. I'll merge and follow-up on the Checkpoint PR. Thanks.

2021-05-26 10:47 UTC, impactmass commented on lesson18/index.md
> +- Look in your project and review how specific your CSS selectors are. See if you can find places you could be using lower specificity while still achieving your styling.
```suggestion
- Look in your project and review how specific your CSS selectors are. See if you can find places you could be using lower specificity while still achieving your styling.
- In [Checkpoint 18](https://github.com/ReDI-School/nrw-html-and-css-2021-spring/blob/checkpoint18), we added comments to our CSS file regarding inheritance and specificity. Take a look at it, and try to find other similar places in your code and label them.
```

2021-05-26 10:48 UTC, merged