Add lesson 19 quiz
ReDI-School/nrw-html-and-css-2021-spring pull request #54
Opened 2021-05-30 20:48 UTC by impactmass

2021-05-31 06:52 UTC, angelsvirkov requested changes
Very good collection of questions. Here is my short feedback

2021-05-31 06:52 UTC, angelsvirkov commented on lesson19/index.md
> +## 2. Quiz
Could we also add a separate file with all the quiz questions and answers (with explanation if needed) because this way we would save this for next semester as well?

2021-05-31 06:52 UTC, angelsvirkov commented on lesson19/index.md
> +
Could you also provide a little bit of explanation for the answer of question 4. I think I get it but I want to be 100% sure

2021-05-31 06:52 UTC, angelsvirkov commented on lesson19/index.md
> +During the class, there will be a quiz to review CSS Cascade, Specificity & Inheritance. A Slido link for the quiz will be shared in the class. Images present in the `quiz` folder of this lesson are
I don't see the image for question 5 and 6?

2021-05-31 06:52 UTC, angelsvirkov commented on lesson19/index.md
> +
I think the answer for question 9 is wrong. The `.body` class is not applied anywhere. Therefore, the font-family on the p would be the default font-family. I suggest adding another answer `default` and making this correct, because it is a nice catch which also teaches students that classNames are different than html tag style definitions.

2021-05-31 07:29 UTC, impactmass commented on lesson19/index.md
> +## 2. Quiz
Good idea. I will make a file with the questions, but maybe we should not merge it until after the class :). I will add it in a branch

2021-05-31 07:29 UTC, impactmass commented on lesson19/index.md
> +
yea, I can

2021-05-31 07:29 UTC, impactmass commented on lesson19/index.md
> +During the class, there will be a quiz to review CSS Cascade, Specificity & Inheritance. A Slido link for the quiz will be shared in the class. Images present in the `quiz` folder of this lesson are
Questions 4,5 and 6 uses the same image lesson19/quiz/exercise-class-2-quiz-image-3.png

2021-05-31 07:29 UTC, impactmass commented on lesson19/index.md
> +
Oh. It's a typo. It's meant to be `body` not `.body`... Please review it again that way, and see if the answer then makes sense.

2021-05-31 11:12 UTC, angelsvirkov commented on lesson19/index.md
> +## 2. Quiz
I think there is no problem if we merge it now. I do not expect people looking around in our GitHub repo. But if they do then it is their responsibility to not cheat. You can't cheat life :D

2021-05-31 11:13 UTC, angelsvirkov commented on lesson19/index.md
> +
Then it would make sense but I was probably aiming at leaving it `.body` as it is the last question and we could make it a little bit more difficult :D

2021-05-31 11:14 UTC, angelsvirkov commented on lesson19/index.md
> +During the class, there will be a quiz to review CSS Cascade, Specificity & Inheritance. A Slido link for the quiz will be shared in the class. Images present in the `quiz` folder of this lesson are
I think the image does not contain B and C

2021-05-31 21:33 UTC, impactmass commented on lesson19/index.md
> +## 2. Quiz
😄 👍

2021-05-31 21:33 UTC, impactmass commented on lesson19/index.md
> +During the class, there will be a quiz to review CSS Cascade, Specificity & Inheritance. A Slido link for the quiz will be shared in the class. Images present in the `quiz` folder of this lesson are
Really? In pink.... A is on the left. B and C on the right. 🧐

2021-05-31 21:33 UTC, impactmass commented on lesson19/index.md
> +
Oh, that would have been nice, but I already recreated the image before reading your comment. Sorry. I left it as `body`.

2021-05-31 21:33 UTC, impactmass commented on lesson19/index.md
> +## 2. Quiz
Quiz file added with explanations

2021-05-31 21:36 UTC, impactmass commented on lesson19/index.md
> +During the class, there will be a quiz to review CSS Cascade, Specificity & Inheritance. A Slido link for the quiz will be shared in the class. Images present in the `quiz` folder of this lesson are
```suggestion
During the class, there will be a quiz to review CSS Cascade, Specificity & Inheritance. The questions for the quiz are in [quiz.md](./quiz/quiz.md). A Slido link will be shared in the class to facilitate the quiz. 
```

2021-06-01 06:49 UTC, angelsvirkov commented on lesson19/index.md
> +During the class, there will be a quiz to review CSS Cascade, Specificity & Inheritance. A Slido link for the quiz will be shared in the class. Images present in the `quiz` folder of this lesson are
Ah yes, I somehow missed that I can horizontally scroll on it. It's there 👍

2021-06-01 06:49 UTC, angelsvirkov commented on lesson19/index.md
> +
Alright 👍

2021-06-01 06:51 UTC, angelsvirkov approved these changes
Good job with the quiz. Original idea and I think the students will like it 💯

2021-06-01 06:53 UTC, angelsvirkov commented on lesson19/index.md
> +During the class, there will be a quiz to review CSS Cascade, Specificity & Inheritance. The questions for the quiz are in [quiz.md](./quiz/quiz.md). A Slido link will be shared in the class to facil
```suggestion
During the class, there will be a quiz to review CSS Cascade, Specificity & Inheritance. The questions for the quiz are in [quiz.md](./quiz/quiz.md) (SPOILER ALERT: Please do not open this link before the quiz is over). A Slido link will be shared in the class to facilitate the quiz. 
```

2021-06-01 06:54 UTC, merged