Checkpoint 24
ReDI-School/nrw-html-and-css-2021-spring pull request #64
Opened 2021-06-24 21:41 UTC by impactmass

Adding transition styles to the project based on [the sandbox we practiced in the class](https://codesandbox.io/s/24-june-part-3-67trp?file=/style.css:2539-2591).

The color schemes could be better, we can improve that later. Here I just added places where transition effect can be added.

2021-06-27 12:08 UTC, angelsvirkov requested changes
I like the idea of adding the read more as an animation. I found the PR a little bit difficult to follow and probably a little bit too complicated for the use case I see. Maybe we can simplify some bits here and there

2021-06-27 12:08 UTC, angelsvirkov commented on checkpoint/css/main.css
> +#projects li:after {
I am not sure I understand the purpose of this pseudo-element here. I moved some of the properties into the `#projects .details` selector and I could achieve similar behaviour. I have some difficulties following along all the classes. I think if we could simplify the rules or eliminate some it would make it easier for the others to understand too. I could be wrong as I am not sure what the purpose of this `:after` is but I assume that it can also be covered by the `#projects .details` and thus we can eliminate this selector

2021-06-27 12:08 UTC, angelsvirkov commented on checkpoint/css/main.css
> +  /* font-style: italic; */
Should we remove this
```suggestion
```

2021-06-27 12:08 UTC, angelsvirkov commented on checkpoint/css/main.css
> +  background-image: linear-gradient(
Is this linear-gradient all needed, maybe we can simplify it to just a couple of lines
```
  background-image: linear-gradient(
    to bottom,
    rgba(2, 44, 0.2, 0.5) 0%,
    rgba(2, 44, 0.2, 1) 30%,
    rgba(2, 44, 0.2, 0.5) 80%
  );
  ```

2021-06-30 19:40 UTC, impactmass commented
> I like the idea of adding the read more as an animation. I found the PR a little bit difficult to follow and probably a little bit too complicated for the use case I see. Maybe we can simplify some bits here and there

@angelsvirkov you're probably right that it could be simplified. What is here is an application of an exercise we used during the class. I couldn't spend time to simplify it further.

2021-07-01 06:42 UTC, angelsvirkov commented
> > I like the idea of adding the read more as an animation. I found the PR a little bit difficult to follow and probably a little bit too complicated for the use case I see. Maybe we can simplify some bits here and there
> 
> @angelsvirkov you're probably right that it could be simplified. What is here is an application of an exercise we used during the class. I couldn't spend time to simplify it further.

Alright, should we merge then?

2021-07-01 07:12 UTC, impactmass commented
> Alright, should we merge then?

I'd say we close the PR. I have opened a feedback PR, to remind for coming semester, about the fact that the checkpoint needs some work. https://github.com/ReDI-School/nrw-html-and-css-2021-spring/pull/66

2021-07-01 07:12 UTC, closed without merging