Lesson3
ReDI-School/nrw-html-and-css-2021-spring pull request #7
Opened 2021-03-23 18:41 UTC by otaruMendez

- Add Glossary & Terminology for Lesson 3 in Students Note
- Add Exercises for Lesson 3

2021-03-23 19:20 UTC, impactmass reviewed
Thanks Babatunde. I added two comments

2021-03-23 19:20 UTC, impactmass commented on lesson3/Create Webpage Exercise.html
> +-->
since this is empty, and you already have a the Exercise described in the index.md, do we still need this file?

2021-03-23 19:20 UTC, impactmass commented on lesson3/index.md
> +- `HTML Tag` - HTML are text(s) in angle brackets and are used in creating HTML elements
```suggestion
- `HTML Tags` - are text(s) in angle brackets and are used in creating HTML elements
```

2021-03-23 19:27 UTC, angelsvirkov requested changes
Thanks for adding these points 🚀 . 
I have added some minor improvement suggestions

2021-03-23 19:27 UTC, angelsvirkov commented on lesson3/index.md
> +- Read about at least ten semantic HTML elements and when to use them.
Could you give an example of which those semantic elements are? I think if students do not have concrete instructions then some of them might get confused

2021-03-23 19:27 UTC, angelsvirkov commented on lesson3/index.md
> +- Read about the different HTML metadata elements
Maybe a resource link would be useful here

2021-03-23 19:27 UTC, angelsvirkov commented on lesson3/index.md
> +- `Browser Viewport` - The browser viewport is the size of the rectangle that a web page fills on your screen
Nice explanation 💯

2021-03-23 19:27 UTC, angelsvirkov commented on lesson3/index.md
> +- `Semantic HTML Element` - Semantic HTML Elements describes its meaning to both the browser and the developer
I am not sure if students will completely understand that part. Could we improve it somehow by adding another sentence. Something like 
```suggestion
- `Semantic HTML Element` - A semantic HTML Elements describes its meaning to both the browser and the developer. In other words, the html tag of a semantic element is very easy to understand by developers. For example, `<table>` is a semantic element that would create a table on the page.
```

2021-03-23 19:27 UTC, angelsvirkov commented on lesson3/index.md
> +- `Charset Encdoing` - Character encoding is used to represent a repertoire of characters by some encoding system that assigns a number to each character for digital representation
Maybe it would be useful if provide a link to further resources if students are interested

2021-03-23 20:00 UTC, otaruMendez commented
Thanks for reviewing, fixed the issues.
Please check again

2021-03-24 07:46 UTC, angelsvirkov approved these changes
Looks good and all feedback has been addressed. Merging

2021-03-24 07:46 UTC, merged